//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/Scripts/InputActions/CharacterControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Game.InputActions
{
    public partial class @CharacterControls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @CharacterControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""CharacterControls"",
    ""maps"": [
        {
            ""name"": ""CharacterController"",
            ""id"": ""58f4d02e-83ab-4b17-9e19-d9ab59660d3e"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""67f70b87-89f0-4e21-ba74-5f63398d8c36"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorPosition"",
                    ""type"": ""Value"",
                    ""id"": ""63ab20a1-f7cd-43c7-9f36-a354fa940240"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9f0250b1-918e-4e59-b570-112f2e70b464"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07b4f464-6a3c-4d55-bf29-3fade23fc0ef"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""QuickActionsController"",
            ""id"": ""d48cfa44-fb11-44f3-83d7-b03a82441579"",
            ""actions"": [
                {
                    ""name"": ""Save"",
                    ""type"": ""Button"",
                    ""id"": ""56d77b6f-a7c8-40d2-a8e8-3aec3c7c53c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Load"",
                    ""type"": ""Button"",
                    ""id"": ""51312e0d-73ed-4963-b949-8ed0128f9d8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6eaf4922-5163-4780-9127-d61c757f5ae6"",
                    ""path"": ""<Keyboard>/f1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Save"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7b4f9043-a9ef-496a-80a9-c344b62763ce"",
                    ""path"": ""<Keyboard>/f2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Load"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        }
    ]
}");
            // CharacterController
            m_CharacterController = asset.FindActionMap("CharacterController", throwIfNotFound: true);
            m_CharacterController_Move = m_CharacterController.FindAction("Move", throwIfNotFound: true);
            m_CharacterController_CursorPosition = m_CharacterController.FindAction("CursorPosition", throwIfNotFound: true);
            // QuickActionsController
            m_QuickActionsController = asset.FindActionMap("QuickActionsController", throwIfNotFound: true);
            m_QuickActionsController_Save = m_QuickActionsController.FindAction("Save", throwIfNotFound: true);
            m_QuickActionsController_Load = m_QuickActionsController.FindAction("Load", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // CharacterController
        private readonly InputActionMap m_CharacterController;
        private ICharacterControllerActions m_CharacterControllerActionsCallbackInterface;
        private readonly InputAction m_CharacterController_Move;
        private readonly InputAction m_CharacterController_CursorPosition;
        public struct CharacterControllerActions
        {
            private @CharacterControls m_Wrapper;
            public CharacterControllerActions(@CharacterControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_CharacterController_Move;
            public InputAction @CursorPosition => m_Wrapper.m_CharacterController_CursorPosition;
            public InputActionMap Get() { return m_Wrapper.m_CharacterController; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CharacterControllerActions set) { return set.Get(); }
            public void SetCallbacks(ICharacterControllerActions instance)
            {
                if (m_Wrapper.m_CharacterControllerActionsCallbackInterface != null)
                {
                    @Move.started -= m_Wrapper.m_CharacterControllerActionsCallbackInterface.OnMove;
                    @Move.performed -= m_Wrapper.m_CharacterControllerActionsCallbackInterface.OnMove;
                    @Move.canceled -= m_Wrapper.m_CharacterControllerActionsCallbackInterface.OnMove;
                    @CursorPosition.started -= m_Wrapper.m_CharacterControllerActionsCallbackInterface.OnCursorPosition;
                    @CursorPosition.performed -= m_Wrapper.m_CharacterControllerActionsCallbackInterface.OnCursorPosition;
                    @CursorPosition.canceled -= m_Wrapper.m_CharacterControllerActionsCallbackInterface.OnCursorPosition;
                }
                m_Wrapper.m_CharacterControllerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Move.started += instance.OnMove;
                    @Move.performed += instance.OnMove;
                    @Move.canceled += instance.OnMove;
                    @CursorPosition.started += instance.OnCursorPosition;
                    @CursorPosition.performed += instance.OnCursorPosition;
                    @CursorPosition.canceled += instance.OnCursorPosition;
                }
            }
        }
        public CharacterControllerActions @CharacterController => new CharacterControllerActions(this);

        // QuickActionsController
        private readonly InputActionMap m_QuickActionsController;
        private IQuickActionsControllerActions m_QuickActionsControllerActionsCallbackInterface;
        private readonly InputAction m_QuickActionsController_Save;
        private readonly InputAction m_QuickActionsController_Load;
        public struct QuickActionsControllerActions
        {
            private @CharacterControls m_Wrapper;
            public QuickActionsControllerActions(@CharacterControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Save => m_Wrapper.m_QuickActionsController_Save;
            public InputAction @Load => m_Wrapper.m_QuickActionsController_Load;
            public InputActionMap Get() { return m_Wrapper.m_QuickActionsController; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(QuickActionsControllerActions set) { return set.Get(); }
            public void SetCallbacks(IQuickActionsControllerActions instance)
            {
                if (m_Wrapper.m_QuickActionsControllerActionsCallbackInterface != null)
                {
                    @Save.started -= m_Wrapper.m_QuickActionsControllerActionsCallbackInterface.OnSave;
                    @Save.performed -= m_Wrapper.m_QuickActionsControllerActionsCallbackInterface.OnSave;
                    @Save.canceled -= m_Wrapper.m_QuickActionsControllerActionsCallbackInterface.OnSave;
                    @Load.started -= m_Wrapper.m_QuickActionsControllerActionsCallbackInterface.OnLoad;
                    @Load.performed -= m_Wrapper.m_QuickActionsControllerActionsCallbackInterface.OnLoad;
                    @Load.canceled -= m_Wrapper.m_QuickActionsControllerActionsCallbackInterface.OnLoad;
                }
                m_Wrapper.m_QuickActionsControllerActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Save.started += instance.OnSave;
                    @Save.performed += instance.OnSave;
                    @Save.canceled += instance.OnSave;
                    @Load.started += instance.OnLoad;
                    @Load.performed += instance.OnLoad;
                    @Load.canceled += instance.OnLoad;
                }
            }
        }
        public QuickActionsControllerActions @QuickActionsController => new QuickActionsControllerActions(this);
        private int m_KeyboardSchemeIndex = -1;
        public InputControlScheme KeyboardScheme
        {
            get
            {
                if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
                return asset.controlSchemes[m_KeyboardSchemeIndex];
            }
        }
        public interface ICharacterControllerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnCursorPosition(InputAction.CallbackContext context);
        }
        public interface IQuickActionsControllerActions
        {
            void OnSave(InputAction.CallbackContext context);
            void OnLoad(InputAction.CallbackContext context);
        }
    }
}
